theme: minima
title: My First Try with Jekyll
author: DavidX
description: I just want to build up a homepage! Wait, also a project page for each of my publication. Can we type equations here? $a^2+b^2=c^2$.
